version: "2"
services:

  odk-sync:
    image: odk/sqlserver_endpoint
    env_file: 
      - .env
      - odk.env
    environment:
      SERVER_URL: ${VIRTUAL_HOST}
      SERVER_PORT: 80
      SERVER_SECURE_PORT: 443
    depends_on: [log]

  odk-sync-consul-register:
    image: odk/openlmis-consul-register:odk-sync
    env_file: 
      - .env
      - odk.env
    environment: 
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      SERVICE_NAME: odk-sync
    depends_on: [odk-sync]